version: 2
jobs:
  build:
    working_directory: ~/retreat-hello-world/frontend
    docker:
      - image: circleci/node:10.16-buster-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: cd frontend && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./frontend/node_modules
      - run:
          name: angular-build
          command: cd frontend && yarn ng build --prod --aot --no-progress
      - run:
          name: angular-test
          command: cd frontend && yarn test --watch=false --no-progress --code-coverage=true
      - store_artifacts:
          path: ./frontend/test-results.xml
          prefix: tests
      - run:
          name: angular-lint
          command: cd frontend && yarn lint --format junit > tslint.xml
      - store_artifacts:
          path: ./frontend/tslint.xml
          prefix: lint
      - run:
          name: install firebase
          command: cd frontend && npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: deploy-to-firebase
          command: cd frontend && ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
      
